// examples/react/SnowComponent.jsx
/**
 * React component for Festive Snow
 *
 * Usage:
 * ```jsx
 * import Snow from './SnowComponent';
 *
 * function App() {
 *   return <Snow intensity="medium" enabled={true} />;
 * }
 * ```
 */

import {useEffect, useRef} from 'react';
import {SnowEffect} from 'festive-snow';

export default function Snow({intensity = 'medium', enabled = true, seasonCheck = null}) {
  const snowRef = useRef(null);

  useEffect(() => {
    // Only create effect if enabled
    if (enabled) {
      const snow = new SnowEffect({
        intensity,
        enabled: true,
        seasonCheck
      });
      snow.init();
      snow.start();
      snowRef.current = snow;

      // Cleanup on unmount
      return () => {
        if (snowRef.current) {
          snowRef.current.stop();
          snowRef.current = null;
        }
      };
    } else {
      // If disabled and snow exists, stop it
      if (snowRef.current) {
        snowRef.current.stop();
        snowRef.current = null;
      }
    }
  }, [enabled, seasonCheck]);

  // Update intensity when it changes
  useEffect(() => {
    if (snowRef.current && enabled) {
      snowRef.current.setIntensity(intensity);
    }
  }, [intensity, enabled]);

  // This component renders nothing
  return null;
}

// examples/vue/SnowComponent.vue
<template>
  <!-- This component renders nothing, it only manages the snow effect -->
</template>

<script setup>
/**
 * Vue 3 component for Festive Snow (Composition API)
 *
 * Usage:
 * ```vue
 * <template>
 *   <Snow intensity="medium" :enabled="true" />
 * </template>
 *
 * <script setup>
 * import Snow from './SnowComponent.vue';
 * </script>
* ```
*/

import { onMounted, onUnmounted, watch } from 'vue';
import { SnowEffect } from 'festive-snow';

const props = defineProps({
intensity: {
type: String,
default: 'medium',
validator: (value) => ['light', 'medium', 'heavy'].includes(value)
},
enabled: {
type: Boolean,
default: true
},
seasonCheck: {
type: Function,
default: null
}
});

let snow = null;

// Create snow effect on mount if enabled
onMounted(() => {
if (props.enabled) {
snow = new SnowEffect({
intensity: props.intensity,
enabled: true,
seasonCheck: props.seasonCheck
});
snow.init();
snow.start();
}
});

// Clean up on unmount
onUnmounted(() => {
if (snow) {
snow.stop();
snow = null;
}
});

// Watch for intensity changes
watch(() => props.intensity, (newIntensity) => {
if (snow && props.enabled) {
snow.setIntensity(newIntensity);
}
});

// Watch for enabled changes
watch(() => props.enabled, (newEnabled) => {
if (newEnabled && !snow) {
// Create and start snow
snow = new SnowEffect({
intensity: props.intensity,
enabled: true,
seasonCheck: props.seasonCheck
});
snow.init();
snow.start();
} else if (!newEnabled && snow) {
// Stop and destroy snow
snow.stop();
snow = null;
}
});
</script>
